#!/bin/bash
# .github/scripts/aggregate-rules.sh
# Aggregates all rule sources into a single context file for PR review
# This script is called by the pr-review.yml workflow

set -euo pipefail

# Define output file
OUTPUT_FILE="${1:-/tmp/review-context.md}"

# Define rule source files in order of authority
CONSTITUTION_FILE=".specify/memory/constitution.md"
AGENTS_FILE="AGENTS.md"
COPILOT_INSTRUCTIONS_FILE=".github/agents/copilot-instructions.md"
SHARED_CONTEXT_FILE=".specify/memory/agent-shared-context.md"

# Function to safely read a file or return a placeholder
read_file_safe() {
    local file="$1"
    local label="$2"
    if [[ -f "$file" ]]; then
        cat "$file"
    else
        echo "<!-- $label not found at $file -->"
    fi
}

# Extract constitution version
extract_constitution_version() {
    if [[ -f "$CONSTITUTION_FILE" ]]; then
        grep -oP '\*\*Version\*\*: \K[0-9]+\.[0-9]+\.[0-9]+' "$CONSTITUTION_FILE" 2>/dev/null || echo "unknown"
    else
        echo "unknown"
    fi
}

# Get constitution version
CONSTITUTION_VERSION=$(extract_constitution_version)

# Generate timestamp
GENERATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Build aggregated context
cat << EOF > "$OUTPUT_FILE"
# PR Review Context

**Generated**: ${GENERATED_AT}
**Constitution Version**: ${CONSTITUTION_VERSION}

---

## Rule Sources Hierarchy

This context aggregates rules from multiple sources in order of authority:

1. **PRIMARY**: Constitution (NON-NEGOTIABLE principles)
2. **SECONDARY**: AGENTS.md (Repository-specific agent rules)
3. **TERTIARY**: Copilot Instructions (Development guidelines)
4. **CONTEXT**: Shared Agent Context (Common patterns)

---

## 1. Constitution Principles (PRIMARY AUTHORITY)

$(read_file_safe "$CONSTITUTION_FILE" "Constitution")

---

## 2. Agent Rules (SECONDARY)

$(read_file_safe "$AGENTS_FILE" "AGENTS.md")

---

## 3. Development Guidelines (TERTIARY)

$(read_file_safe "$COPILOT_INSTRUCTIONS_FILE" "Copilot Instructions")

---

## 4. Shared Context (SUPPLEMENTARY)

$(read_file_safe "$SHARED_CONTEXT_FILE" "Shared Agent Context")

---

## Review Instructions

When reviewing code changes, apply the following validation categories:

### Critical (Blocking)
- TypeScript strict mode violations (no implicit \`any\`)
- Missing tests for business logic
- Security vulnerabilities (secrets in code, missing input validation)
- DynamoDB scan operations (must use queries with indexes)

### High (Strongly Recommended)
- AWS SDK v3 modular import violations
- Missing error handling for AWS calls
- CORS/security header issues

### Medium (Advisory)
- Code organization issues
- Missing type definitions
- Performance optimization opportunities

### Low (Informational)
- Style inconsistencies
- Documentation improvements
- Minor refactoring suggestions

---

*This context was auto-generated by aggregate-rules.sh*
EOF

# Output the path for workflow consumption
echo "Review context generated at: $OUTPUT_FILE"
echo "Constitution version: $CONSTITUTION_VERSION"

# Also output as GitHub Actions output if running in CI
if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    echo "context_file=$OUTPUT_FILE" >> "$GITHUB_OUTPUT"
    echo "constitution_version=$CONSTITUTION_VERSION" >> "$GITHUB_OUTPUT"
fi